### ISSUE TITLE
Doesn't work in bootstrap modal

### ISSUE THREAD

**Issue by thonythony** [TerryMooreII/angular-wysiwyg#25]
It seems that the fragment of the menu isn't appended in its container "div.wysiwyg-menu", when the directive is called in a modal window.

``TypeError: Cannot read property 'appendChild' of null
    at Object.createMenu (http://localhost:1337/lib/angular-wysiwyg.min.js:313:14)
    at Object.compile (http://localhost:1337/lib/angular-wysiwyg.min.js:54:17)
    at applyDirectivesToNode (http://localhost:1337/lib/angular.js:7459:32)
    at compileNodes (http://localhost:1337/lib/angular.js:7000:15)
    at compileNodes (http://localhost:1337/lib/angular.js:7012:15)
    at compileNodes (http://localhost:1337/lib/angular.js:7012:15)
    at compile (http://localhost:1337/lib/angular.js:6907:15)
    at applyDirectivesToNode (http://localhost:1337/lib/angular.js:7386:33)
    at compileNodes (http://localhost:1337/lib/angular.js:7000:15)
    at compile (http://localhost:1337/lib/angular.js:6907:15) <div textarea-id="inputText" textarea-class="form-control" textarea-height="120px" textarea-name="inputText" textarea-required="" ng-model="message.text" enable-bootstrap-title="false">``

**Comment by mohammedJ** [comment]
For me, the menu shows up but when i click on one of the buttons, the page reloads.
This seems to only happen when using it in a modal.

**Comment by TerryMooreII** [comment]
@thonythony Which version of are you currently using?  I have never tested in a modal but I will and let you know what I find out.

**Comment by MTijn** [comment]
I seemed to have the same problem @mohammedJ had, the solution for me was to replace the ng-submit="submit()" from the form element.

Replaced that with a ng-click attribute on the submit button and all is working fine for me right now.

**Comment by TerryMooreII** [comment]
I believe I have this issue fixed with Fix #38.  Reopen this ticket if you are still having issues with the latest version
