### ISSUE TITLE
Is this component dependent on jQuery?

### ISSUE THREAD

**Issue by mdentinho** [TerryMooreII/angular-wysiwyg#48]
After adding it to my project, it I throws this error:

```bash
Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite!
```
But the README.md Required dependancies doesn't have jQuery.

**Comment by TerryMooreII** [comment]
Yes, currently but my long term goal is to remove that dependancy.  Also I thought that I updated the docs but apparently I forgot.  Thanks for the reminder.

**Comment by parallelepiped** [comment]
Bump. This really changes usability for me.

**Comment by wadeos** [comment]
@parallelepiped - Try this. Its a pure angular fork of this - https://github.com/wadeos/angular-wysiwyg

**Comment by finalcut** [comment]
@wadeos I just tried your fork and I get the same errors
```
peError: s.find(...).tooltip is not a function
    at f (http://localhost:9000/jspm_packages/github/wadeos/angular-wysiwyg@1.2.4/dist/angular-wysiwyg.min.js:1:1004)
    at u (http://localhost:9000/jspm_packages/github/wadeos/angular-wysiwyg@1.2.4/dist/angular-wysiwyg.min.js:1:508)
    at l (http://localhost:9000/jspm_packages/github/wadeos/angular-wysiwyg@1.2.4/dist/angular-wysiwyg.min.js:1:3902)
    at http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:8743:44
    at invokeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:8749:9)
    at nodeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:8249:11)
    at compositeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7640:13)
    at compositeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7644:13)
    at compositeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7644:13)
    at compositeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7644:13)
    at compositeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7644:13)
    at nodeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:8244:24)
    at compositeLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7640:13)
    at publicLinkFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7515:30)
    at name.$get.boundTranscludeFn (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:7659:16)
    at controllersBoundTransclude (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.5/angular.js:8276:18) <div disabled="disabled" textarea-id="message{{ctrl.model.id}}" textarea-class="form-control" textarea-name="message" ng-model="ctrl.model.message" enable-bootstrap-title="true" textarea-height="80px" textarea-required="" class="ng-isolate-scope">(anonymous function) @ angular.js:12419ident.$get @ angular.js:9206invokeLinkFn @ angular.js:8751nodeLinkFn @ angular.js:8249compositeLinkFn @ angular.js:7640compositeLinkFn @ angular.js:7644compositeLinkFn @ angular.js:7644compositeLinkFn @ angular.js:7644compositeLinkFn @ angular.js:7644nodeLinkFn @ angular.js:8244compositeLinkFn @ angular.js:7640publicLinkFn @ angular.js:7515name.$get.boundTranscludeFn @ angular.js:7659controllersBoundTransclude @ angular.js:8276ngIfWatchAction @ angular.js:23887parent.$get.Scope.$digest @ angular.js:15718parent.$get.Scope.$apply @ angular.js:15989done @ angular.js:10514completeRequest @ angular.js:10686requestLoaded @ angular.js:10627
angular.js:12419 Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
http://errors.angularjs.org/1.4.5/jqLite/nosel
    at REGEX_STRING_REGEXP (angular.js:71)
    at Object.JQLite [as element] (angular.js:2779)
    at Object.fn (angular-wysiwyg.min.js:1)
    at Scope.parent.$get.Scope.$digest (angular.js:15718)
    at Scope.parent.$get.Scope.$apply (angular.js:15989)
    at done (angular.js:10514)
    at completeRequest (angular.js:10686)
    at XMLHttpRequest.requestLoaded (angular.js:10627)
```

**Comment by finalcut** [comment]
note if using JSPM to install wadeos version you need to specify @master..

```
jspm install angular-wysiwyg=github:wadeos/angular-wysiwyg@master
```
