### ISSUE TITLE
jqLite Error

### ISSUE THREAD

**Issue by Bnaoufal** [TerryMooreII/angular-wysiwyg#63]
angular.js:13550 Error: [jqLite:nosel] http://errors.angularjs.org/1.5.5/jqLite/nosel
    at Error (native)
    at http://localhost:8080/outil-evaluation/front/bower_components/angular/angular.min.js:6:412
    at Object.U [as element] (http://localhost:8080/outil-evaluation/front/bower_components/angular/angular.min.js:31:207)
    at configureListeners (http://localhost:8080/outil-evaluation/front/bower_components/angular-wysiwyg/src/angular-wysiwyg.js:202:29)
    at init (http://localhost:8080/outil-evaluation/front/bower_components/angular-wysiwyg/src/angular-wysiwyg.js:164:21)
    at link (http://localhost:8080/outil-evaluation/front/bower_components/angular-wysiwyg/src/angular-wysiwyg.js:157:17)
    at http://localhost:8080/outil-evaluation/front/bower_components/angular/angular.min.js:80:293
    at ja (http://localhost:8080/outil-evaluation/front/bower_components/angular/angular.min.js:80:350)
    at n (http://localhost:8080/outil-evaluation/front/bower_components/angular/angular.min.js:66:28)
    at g (http://localhost:8080/outil-evaluation/front/bower_components/angular/angular.min.js:58:305) <div textarea-class="form-control" ng-model="gestionReferentiel.message" class="ng-isolate-scope">

**Comment by TerryMooreII** [comment]
This currently requires jquery.
