### ISSUE TITLE
failing on start "element.find(...).tooltip is not a function"

### ISSUE THREAD

**Issue by rafaelcoutinho** [TerryMooreII/angular-wysiwyg#64]
Not sure what I've missed, but always getting this error:

 ```
element.find(...).tooltip is not a function
    at configureBootstrapTitle (http://app.northbrasil.com.br/bower_components/angular-wysiwyg/dist/angular-wysiwyg.js:203:43)
    at init (http://app.northbrasil.com.br/bower_components/angular-wysiwyg/dist/angular-wysiwyg.js:182:11)
    at link (http://app.northbrasil.com.br/bower_components/angular-wysiwyg/dist/angular-wysiwyg.js:178:9)
```

**Comment by middink** [comment]
i have same problem @rafaelcoutinho

**Comment by rafaelcoutinho** [comment]
I is related to this tag 
`enable-bootstrap-title="true"`

set it to false and it works.
